name: Sign and Verify Image with Cosign

on:
  push:
    branches:
      - main
#test
jobs:
  cosign:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Upstream: https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        uses: sigstore/cosign-installer@cad07c2e89fa2edd6e2d7bab4c1aa38e53f76003

      - name: Verify Cosign installation
        run: cosign version

  crane:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Upstream: https://github.com/imjasonh/setup-crane
      - name: Install Crane
        uses: imjasonh/setup-crane@6da1ae018866400525525ce74ff892880c099987

      - name: Verify Crane installation
        run: crane version
