name: Sign and Verify Image with Cosign

on:
  push:
    branches:
      - main

jobs:
  cosign:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Upstream: https://github.com/sigstore/cosign-installer
      - name: Install Cosign
        uses: chainguard-actions/sigstore--cosign-installer@v4.1.1

      - name: Verify Cosign installation
        run: cosign version

  crane:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    # Upstream: https://github.com/imjasonh/setup-crane
      - name: Install Crane
        uses: chainguard-actions/imjasonh--setup-crane@v0.5

      - name: Verify Crane installation
        run: crane version
